version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: >-
    nuget.exe restore GDAXSharp.sln

    GitVersion.exe /output buildserver
build:
  project: GDAXSharp.sln
  verbosity: normal
test:
  assemblies:
    only:
    - '**\*.Specs.dll'