language: csharp
solution: GDAXClient.sln
script:
  - xbuild /p:Configuration=Release GDAXClient.sln
  - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./GDAXClient.Specs/bin/Release/GDAXClient.Specs.dll
